# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decimalFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DecimalFrameUI(object):
    def setupUi(self, Frame):

        Frame.setObjectName("Frame")
        Frame.resize(392, 207)
        Frame.setAutoFillBackground(True)
        Frame.setFrameShape(QtWidgets.QFrame.Box)

        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(90, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(110, 80, 181, 41))
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(140, 140, 121, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Set number of decimal places"))
        self.pushButton.setText(_translate("Frame", "Okay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = DecimalFrameUI()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
